### ISSUE TITLE
mysql setting owner to systemd-coredump. Can't stop it.

### ISSUE THREAD

**Issue by oregonpillow** [Ombi-app/Ombi#4369]
**Describe the bug**
Can't stop mysql files having owner set as `systemd-coredump`. I tried explicitly passing in PUID/PGID to mysql_db & phpmyadmin but doesn't make difference.

```
(base) ................/ombi/mysql$ ls -lh
total 185M
-rw-r----- 1 systemd-coredump users              56 Oct 16 19:44 auto.cnf
-rw------- 1 systemd-coredump users            1.7K Oct 16 19:44 ca-key.pem
-rw-r--r-- 1 systemd-coredump users            1.1K Oct 16 19:44 ca.pem
-rw-r--r-- 1 systemd-coredump users            1.1K Oct 16 19:44 client-cert.pem
-rw------- 1 systemd-coredump users            1.7K Oct 16 19:44 client-key.pem
-rw-r----- 1 systemd-coredump systemd-coredump  396 Oct 22 20:35 ib_buffer_pool
-rw-r----- 1 systemd-coredump users             76M Oct 22 20:36 ibdata1
-rw-r----- 1 systemd-coredump users             48M Oct 22 20:36 ib_logfile0
-rw-r----- 1 systemd-coredump users             48M Oct 16 19:44 ib_logfile1
-rw-r----- 1 systemd-coredump systemd-coredump  12M Oct 22 20:36 ibtmp1
drwxr-x--- 2 systemd-coredump users            4.0K Oct 16 19:44 mysql
drwxr-x--- 2 systemd-coredump users            4.0K Oct 16 19:47 Ombi
drwxr-x--- 2 systemd-coredump users            4.0K Oct 16 19:47 Ombi_External
drwxr-x--- 2 systemd-coredump users            4.0K Oct 16 19:47 Ombi_Settings
drwxr-x--- 2 systemd-coredump users            4.0K Oct 16 19:44 performance_schema
-rw------- 1 systemd-coredump users            1.7K Oct 16 19:44 private_key.pem
-rw-r--r-- 1 systemd-coredump users             452 Oct 16 19:44 public_key.pem
-rw-r--r-- 1 systemd-coredump users            1.1K Oct 16 19:44 server-cert.pem
-rw------- 1 systemd-coredump users            1.7K Oct 16 19:44 server-key.pem
drwxr-x--- 2 systemd-coredump users             12K Oct 16 19:44 sys
```
```
version: "3"
services:
  ombi:
    image: ghcr.io/linuxserver/ombi:latest
    container_name: ombi
    network_mode: lsio
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - BASE_URL=/ombi
    volumes:
      - ./config:/config
    ports:
      - "3579:3579"
    depends_on:
    - "mysql_db"


  mysql_db:
    image: "mysql:5.7"
    container_name: ombi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: blablabla........
    volumes:
      -  ./mysql:/var/lib/mysql


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: ombi_phpmyadmin
      restart: unless-stopped
      environment:
        PMA_HOST: mysql_db
      ports:
        - '8081:80'
      depends_on:
        - "mysql_db"
```
