### ISSUE TITLE
Ombi not reading database.json - new install

### ISSUE THREAD

**Issue by Lebowski89** [Ombi-app/Ombi#5226]
### Summary

Hello,

Have been using Ombi with Mariadb for a while now - deployed as docker swarm services with everything automated via ansible (including templating and copying the database.json into the config directory). Yesterday, I deleted the Mariadb and Ombi and redeployed - but the new Ombi gets stuck on the Wizard even with the database.json in place.

Things I've checked:

- Mariadb user and database exists
- database.json is in the config directory with puid/pgid 1000:1000
- Ombi has 1000:1000 puid/pgid env values - config directory is correct
- Any sqlite db files are removed from the config dir
- The database.json is of correct formatting with expected values
- Made sure database and Ombi are on the same docker overlay network
- Within database.json - have tried it with 
       . database service name (requests-db) + database service container port (5432)
       . machine ip (192.168....) + database service host (5434) port
- Tried opening in different browsers / on different devices

I then tried setting the database as Postgres, as I also deploy this database in the same swarm stack and I know it successfully connects to Jellyseerr (also in the same swarm stack). The result is the same - stuck in wizard. I then tried deleting the database.json that I placed in the config directory and followed through with the wizard - Ombi successfully created its own database.json and asked me to restart, only for it to restart into the wizard back to square zero. 

Swarm stack:

```
version: '3.9'

services:
  {{ ombi_defaults_name }}:
    image: {{ ombi_defaults_image_repo }}:{{ ombi_defaults_image_tag }}
    networks:
      - {{ network_overlay }}
    environment:
      PUID: '{{ puid }}'
      PGID: '{{ pgid }}'
      TZ: '{{ timezone }}'
      UMASK: '022'
    ports:
      - target: {{ ombi_defaults_ports_cont }}
        published: {{ ombi_defaults_ports_host }}
        protocol: tcp
        mode: ingress
    volumes:
      - type: bind
        source: {{ ombi_defaults_location }}
        target: /config
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.ansible_host == pvr]
      labels: {{ ombi_defaults_labels }}

  {{ requests_db_defaults_name }}:
    image: {{ requests_db_defaults_image_repo }}:{{ requests_db_defaults_image_tag }}
    networks:
      - {{ network_overlay }}
    environment:
      TZ: '{{ timezone }}'
      POSTGRES_USER_FILE: /run/secrets/postgres_user_secret
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass_secret
    secrets:
      - postgres_user_secret
      - postgres_pass_secret
    ports:
      - target: {{ requests_db_defaults_ports_cont }}
        published: {{ requests_db_defaults_ports_host }}
        protocol: tcp
        mode: ingress
    volumes:
      - type: bind
        source: {{ requests_db_defaults_location }}
        target: /var/lib/postgresql/data
    user: '{{ puid }}:{{ pgid }}'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.ansible_host == pvr]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  {{ network_overlay }}:
    external: true

volumes:
  {{ appdata_volume }}:
    external: true

secrets:
  postgres_user_secret:
    external: true

  postgres_pass_secret:
    external: true
```

Database JSON:

![Image](https://github.com/user-attachments/assets/2156daa4-5eee-43fc-9778-ac30f4b99b2e)

Looking inside the Postgres Database (via Adminer using the same username/password supplied in Database JSON):

![Image](https://github.com/user-attachments/assets/a84107f2-2662-43f8-a2b8-16a2a2472ede)

Docker/OS Info:
```
Client: Docker Engine - Community
 Version:    28.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.21.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.33.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

 Kernel Version: 6.1.0-31-amd64
 Operating System: Debian GNU/Linux 12 (bookworm)
 OSType: linux
 Architecture: x86_64
```

Any ideas here? Thanks

### Ombi Version

v4.47.1-ls216

### What platform(s) does this occur on?

Docker

### What database are you using?

MySQL

### Relevant log output

```shell
[migrations] started

[migrations] no migrations found

───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗

      ██║     ██╔════╝██║██╔═══██╗

      ██║     ███████╗██║██║   ██║

      ██║     ╚════██║██║██║   ██║

      ███████╗███████║██║╚██████╔╝

      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io

───────────────────────────────────────

To support the app dev(s) visit:

Ombi - Patreon: https://patreon.com/tidusjar

Ombi - PayPal: https://paypal.me/PlexRequestsNet

To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1000

User GID:    1000

───────────────────────────────────────

Linuxserver.io version: v4.47.1-ls216

Build-date: 2025-03-22T22:35:46+00:00

───────────────────────────────────────

    

[custom-init] No custom files found, skipping...

Hello, welcome to Ombi

Valid options are:

Ombi 4.47.1+41e3e760d03fbd6e03ec40dafd0b0eea5f9a5d8c

Copyright (C) 2025 Ombi

  --host       (Default: http://*:5000) Set to a semicolon-separated (;) list of

               URL prefixes to which the server should respond. For example,

               http://localhost:123. Use "localhost" to indicate that the server

               should listen for requests on any IP address or hostname using

               the specified port and protocol (for example,

               http://localhost:5000). The protocol (http:// or https://) must

               be included with each URL. Supported formats vary between

               servers.

  --storage    Storage path, where we save the logs and database

  --baseurl    The base URL for reverse proxy scenarios

  --demo       Demo mode, you will never need to use this, fuck that fruit

               company...

  --migrate    Will run the migrations then exit the application

  --help       Display this help screen.

  --version    Display version information.

Creating new Settings entity

Wrote new baseurl at /app/ombi/ClientApp/dist/index.html

We are running on http://*:3579
```
